---
- name: Create the Resource Group in the specified region
  hosts: localhost
  vars_files:
    - vars/vars.yml
  connection: local
  
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ region }}"
