---
- name: Create the Public IP Address
  hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml
  
  tasks:
    # Public IP Linux VM
    - name: Create public IP address for Linux
      azure_rm_publicipaddress:
        location: "{{ region }}"
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ linux_public_ip_name }}"
