---
- name: Create the Azure Windows Virtual Machine
  hosts: localhost
  connection: local
  tasks:

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ win_vm_name }}"
        os_type: "Windows"
        vm_size: "{{ win_vm_size }}"
        managed_disk_type: Standard_LRS
        admin_username: "{{ win_admin_user }}"
        admin_password: "{{ win_admin_password }}"
        network_interfaces: "{{ win_nic_name }}"
        storage_account_name: "{{ win_vm_name_sa }}"
        os_disk_name: "winos"
        os_disk_size_gb: "150"
        ssh_password_enabled: "false"
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: "{{ win_vm_sku }}"
          version: latest
