
---
- name: Create the Azure Linux Virtual Machine
  hosts: localhost
  connection: local
  tasks:

    - name: Create Network Security Group that allows SSH and RDP
      azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ resource_group_name }}"
      name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: HTTPS
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: http
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1003
            direction: Inbound
    
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ linux_public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux_vm_name }}"
        vm_size: "{{ linux_vm_size }}"
        admin_username: "{{ linux_admin_user }}"
        admin_password: "{{ linux_admin_password }}"
        managed_disk_type: "{{ disk_type }}"
        network_interfaces: "{{ linux_nic_name }}"
        open_ports: "{{ open_ports_vm }}"
        ssh_public_keys:
          - path: "{{ path_public_key }}"
            key_data: "{{ public_ssh_key }}"
        image:
          started: "{{ started_the_vm }}"
          offer: "{{ offer_rhel }}"
          publisher: "{{ publisher_redhat }}"
          sku: "{{ linux_vm_sku }}"
          version: "{{ version_rhel }}"
        #####################################
        #plan: 
          #name: "RHEL Plan"
          #product: "RHEL"
          #publisher: "RedHat"
    
      

