---
- name: Create the Azure Linux Virtual Machine
  hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml
  
  tasks:

  - name: Create a Linux virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ linux_public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"

    - name: Create a second Linux virtual network interface card for 2 second RHEL VM
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux1_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ linux_public_ip_name1 }}"
        security_group: "{{ network_sec_group_name }}"
        
    - name: Create VM RHEL01
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux_vm_name }}"
        vm_size: "{{ linux_vm_size }}"
        admin_username: "{{ linux_admin_user }}"
        admin_password: "{{ linux_admin_password }}"
        managed_disk_type: "{{ disk_type }}"
        network_interfaces: "{{ linux_nic_name }}"
        open_ports: "{{ open_ports_vm }}"
        ssh_public_keys:
          - path: "{{ path_public_key }}"
            key_data: "{{ public_ssh_key }}"
        image:
          started: "{{ started_the_vm }}"
          offer: "{{ offer_rhel }}"
          publisher: "{{ publisher_redhat }}"
          sku: "{{ linux_vm_sku }}"
          version: "{{ version_rhel }}"
        #####################################
        #plan: 
          #name: "RHEL Plan"
          #product: "RHEL"
          #publisher: "RedHat"

    - name: Create VM RHEL02
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux_vm_name1 }}"
        vm_size: "{{ linux_vm_size }}"
        admin_username: "{{ linux_admin_user }}"
        admin_password: "{{ linux_admin_password }}"
        managed_disk_type: "{{ disk_type }}"
        network_interfaces: "{{ linux1_nic_name }}"
        open_ports: "{{ open_ports_vm }}"
        ssh_public_keys:
          - path: "{{ path_public_key }}"
            key_data: "{{ public_ssh_key }}"
        image:
          started: "{{ started_the_vm }}"
          offer: "{{ offer_rhel }}"
          publisher: "{{ publisher_redhat }}"
          sku: "{{ linux_vm_sku }}"
          version: "{{ version_rhel }}"
      

