---
- name: Create Resource Group
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ region }}"
