---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ region }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "{{ vnet_cidr }}"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_cidr }}"
        virtual_network: "{{ vnet_name }}"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ win_public_ip_name }}"
      register: output_ip_address

    - name: Dump public IP for VM which will be created
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Set Stat for Ansible Controller
      set_stats:
        data: 
          azure_vm_public_ip: "{{ output_ip_address.state.ip_address }}"
        per_host: false

    - name: Create Network Security Group that allows SSH and RDP
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: RDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1002
            direction: Inbound
          - name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ win_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ win_public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ win_vm_name }}"
        os_type: Windows
        vm_size: "{{ win_vm_size }}"
        admin_username: "{{ win_admin_user }}"
        admin_password: "{{ win_admin_password }}"
        network_interfaces: "{{ win_nic_name }}"
        tags:
          "name": "{{ win_vm_name }}"
          "demo": "true"
          "os": "windows"
          "username": "{{ win_admin_user }}"
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: "{{ win_vm_sku }}"
          version: latest
